use_sim_time: True
ignore_polarity: True
time_surface_mode: 1 # 0: Backward; 1: Forward
decay_ms: 10
time_surface_at_most_recent_event: True
median_blur_kernel_size: 1
max_event_queue_len: 10 # no more than this at each pixel
